schemaVersion: 2.0.0
commandTests:
  - name: "poetry python"
    command: "poetry"
    args: ["run", "which", "python3"]
    expectedOutput: ["/usr/local/bin/python3"]
  - name: "python3 version"
    command: "python3"
    args: ["--version"]
    expectedOutput: ["Python 3.13.*"]
  - name: "poetry"
    command: "which"
    args: ["poetry"]
    expectedOutput: ["/usr/bin/poetry"]
  - name: "poetry version"
    command: "poetry"
    args: ["--version"]
    expectedOutput: ["Poetry (version 1.6*)*"]
  - name: "poetry python version"
    command: "poetry"
    args: ["run", "python3", "--version"]
    expectedOutput: ["Python 3.13.*"]
  - name: "powershell which"
    command: "which"
    args: ["pwsh"]
    expectedOutput: ["/usr/bin/pwsh"]
  - name: "powershell version"
    command: "pwsh"
    args: ["--version"]
    expectedOutput: ["PowerShell 7.*"]
  - name: "ps-empire help"
    command: "./ps-empire"
    args: ["-f", "server", "--help"]
    expectedOutput: ["usage: empire.py server [-h]*"]
  - name: "ps-empire version"
    command: "./ps-empire"
    args: ["-f", "server", "--version"]
    expectedOutput: ["6.* BC Security Fork"]
  - name: "go which"
    command: "which"
    args: ["go"]
    expectedOutput: ["/usr/bin/go"]
  - name: "go version"
    command: "go"
    args: ["version"]
    expectedOutput: ["go version go1.23.* linux/*"]
fileExistenceTests:
  - name: 'profiles'
    path: '/empire/empire/server/data/profiles/'
    shouldExist: true
  - name: 'starkiller'
    path: '/root/.local/share/empire/starkiller/'
    shouldExist: true
